/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * Parking Management API
 * API for managing users, parking levels, vehicles, and transactions for a parking facility.
This documentation provides a base for all the resources defined in the database schema.

 * OpenAPI spec version: 1.0.0
 */
import { faker } from "@faker-js/faker";
import type { RequestHandlerOptions } from "msw";
import { delay, HttpResponse, http } from "msw";

import type {
	BaseResponse,
	MemberArrayResponse,
	MemberResponse,
	TransactionArrayResponse,
} from ".././models";

export const getListMembersResponseMock = (): MemberArrayResponse => ({
	...{
		success: faker.datatype.boolean(),
		message: faker.string.alpha({ length: { min: 10, max: 20 } }),
	},
	...{
		data: Array.from(
			{ length: faker.number.int({ min: 1, max: 10 }) },
			(_, i) => i + 1,
		).map(() => ({
			id: faker.number.int({ min: undefined, max: undefined }),
			userId: faker.number.int({ min: undefined, max: undefined }),
			joinedAt: `${faker.date.past().toISOString().split(".")[0]}Z`,
			endedAt: `${faker.date.past().toISOString().split(".")[0]}Z`,
		})),
	},
});

export const getCreateMemberResponseMock = (): MemberResponse => ({
	...{
		success: faker.datatype.boolean(),
		message: faker.string.alpha({ length: { min: 10, max: 20 } }),
	},
	...{
		data: {
			id: faker.number.int({ min: undefined, max: undefined }),
			userId: faker.number.int({ min: undefined, max: undefined }),
			joinedAt: `${faker.date.past().toISOString().split(".")[0]}Z`,
			endedAt: `${faker.date.past().toISOString().split(".")[0]}Z`,
		},
	},
});

export const getGetMemberByIdResponseMock = (): MemberResponse => ({
	...{
		success: faker.datatype.boolean(),
		message: faker.string.alpha({ length: { min: 10, max: 20 } }),
	},
	...{
		data: {
			id: faker.number.int({ min: undefined, max: undefined }),
			userId: faker.number.int({ min: undefined, max: undefined }),
			joinedAt: `${faker.date.past().toISOString().split(".")[0]}Z`,
			endedAt: `${faker.date.past().toISOString().split(".")[0]}Z`,
		},
	},
});

export const getUpdateMemberResponseMock = (): MemberResponse => ({
	...{
		success: faker.datatype.boolean(),
		message: faker.string.alpha({ length: { min: 10, max: 20 } }),
	},
	...{
		data: {
			id: faker.number.int({ min: undefined, max: undefined }),
			userId: faker.number.int({ min: undefined, max: undefined }),
			joinedAt: `${faker.date.past().toISOString().split(".")[0]}Z`,
			endedAt: `${faker.date.past().toISOString().split(".")[0]}Z`,
		},
	},
});

export const getDeleteMemberResponseMock = (
	overrideResponse: Partial<BaseResponse> = {},
): BaseResponse => ({
	success: faker.datatype.boolean(),
	message: faker.string.alpha({ length: { min: 10, max: 20 } }),
	...overrideResponse,
});

export const getRenewCurrentMemberResponseMock = (): MemberResponse => ({
	...{
		success: faker.datatype.boolean(),
		message: faker.string.alpha({ length: { min: 10, max: 20 } }),
	},
	...{
		data: {
			id: faker.number.int({ min: undefined, max: undefined }),
			userId: faker.number.int({ min: undefined, max: undefined }),
			joinedAt: `${faker.date.past().toISOString().split(".")[0]}Z`,
			endedAt: `${faker.date.past().toISOString().split(".")[0]}Z`,
		},
	},
});

export const getGetCurrentMemberTransactionsResponseMock =
	(): TransactionArrayResponse => ({
		...{
			success: faker.datatype.boolean(),
			message: faker.string.alpha({ length: { min: 10, max: 20 } }),
		},
		...{
			data: Array.from(
				{ length: faker.number.int({ min: 1, max: 10 }) },
				(_, i) => i + 1,
			).map(() => ({
				id: faker.number.int({ min: undefined, max: undefined }),
				status: faker.helpers.arrayElement(["ENTRY", "EXIT"] as const),
				paidAmount: faker.helpers.arrayElement([
					faker.number.float({
						min: undefined,
						max: undefined,
						fractionDigits: 2,
					}),
					null,
				]),
				accessCode: faker.string.alpha({ length: { min: 10, max: 20 } }),
				userId: faker.helpers.arrayElement([
					faker.number.int({ min: undefined, max: undefined }),
					null,
				]),
				vehicleDetailId: faker.number.int({ min: undefined, max: undefined }),
				parkingLevelId: faker.number.int({ min: undefined, max: undefined }),
				createdAt: `${faker.date.past().toISOString().split(".")[0]}Z`,
				updatedAt: `${faker.date.past().toISOString().split(".")[0]}Z`,
			})),
		},
	});

export const getListMembersMockHandler = (
	overrideResponse?:
		| MemberArrayResponse
		| ((
				info: Parameters<Parameters<typeof http.get>[1]>[0],
		  ) => Promise<MemberArrayResponse> | MemberArrayResponse),
	options?: RequestHandlerOptions,
) => {
	return http.get(
		"*/members",
		async (info) => {
			await delay(1000);

			return new HttpResponse(
				JSON.stringify(
					overrideResponse !== undefined
						? typeof overrideResponse === "function"
							? await overrideResponse(info)
							: overrideResponse
						: getListMembersResponseMock(),
				),
				{ status: 200, headers: { "Content-Type": "application/json" } },
			);
		},
		options,
	);
};

export const getCreateMemberMockHandler = (
	overrideResponse?:
		| MemberResponse
		| ((
				info: Parameters<Parameters<typeof http.post>[1]>[0],
		  ) => Promise<MemberResponse> | MemberResponse),
	options?: RequestHandlerOptions,
) => {
	return http.post(
		"*/members",
		async (info) => {
			await delay(1000);

			return new HttpResponse(
				JSON.stringify(
					overrideResponse !== undefined
						? typeof overrideResponse === "function"
							? await overrideResponse(info)
							: overrideResponse
						: getCreateMemberResponseMock(),
				),
				{ status: 201, headers: { "Content-Type": "application/json" } },
			);
		},
		options,
	);
};

export const getGetMemberByIdMockHandler = (
	overrideResponse?:
		| MemberResponse
		| ((
				info: Parameters<Parameters<typeof http.get>[1]>[0],
		  ) => Promise<MemberResponse> | MemberResponse),
	options?: RequestHandlerOptions,
) => {
	return http.get(
		"*/members/:id",
		async (info) => {
			await delay(1000);

			return new HttpResponse(
				JSON.stringify(
					overrideResponse !== undefined
						? typeof overrideResponse === "function"
							? await overrideResponse(info)
							: overrideResponse
						: getGetMemberByIdResponseMock(),
				),
				{ status: 200, headers: { "Content-Type": "application/json" } },
			);
		},
		options,
	);
};

export const getUpdateMemberMockHandler = (
	overrideResponse?:
		| MemberResponse
		| ((
				info: Parameters<Parameters<typeof http.put>[1]>[0],
		  ) => Promise<MemberResponse> | MemberResponse),
	options?: RequestHandlerOptions,
) => {
	return http.put(
		"*/members/:id",
		async (info) => {
			await delay(1000);

			return new HttpResponse(
				JSON.stringify(
					overrideResponse !== undefined
						? typeof overrideResponse === "function"
							? await overrideResponse(info)
							: overrideResponse
						: getUpdateMemberResponseMock(),
				),
				{ status: 200, headers: { "Content-Type": "application/json" } },
			);
		},
		options,
	);
};

export const getDeleteMemberMockHandler = (
	overrideResponse?:
		| BaseResponse
		| ((
				info: Parameters<Parameters<typeof http.delete>[1]>[0],
		  ) => Promise<BaseResponse> | BaseResponse),
	options?: RequestHandlerOptions,
) => {
	return http.delete(
		"*/members/:id",
		async (info) => {
			await delay(1000);

			return new HttpResponse(
				JSON.stringify(
					overrideResponse !== undefined
						? typeof overrideResponse === "function"
							? await overrideResponse(info)
							: overrideResponse
						: getDeleteMemberResponseMock(),
				),
				{ status: 200, headers: { "Content-Type": "application/json" } },
			);
		},
		options,
	);
};

export const getRenewCurrentMemberMockHandler = (
	overrideResponse?:
		| MemberResponse
		| ((
				info: Parameters<Parameters<typeof http.post>[1]>[0],
		  ) => Promise<MemberResponse> | MemberResponse),
	options?: RequestHandlerOptions,
) => {
	return http.post(
		"*/members/me/renew",
		async (info) => {
			await delay(1000);

			return new HttpResponse(
				JSON.stringify(
					overrideResponse !== undefined
						? typeof overrideResponse === "function"
							? await overrideResponse(info)
							: overrideResponse
						: getRenewCurrentMemberResponseMock(),
				),
				{ status: 200, headers: { "Content-Type": "application/json" } },
			);
		},
		options,
	);
};

export const getGetCurrentMemberTransactionsMockHandler = (
	overrideResponse?:
		| TransactionArrayResponse
		| ((
				info: Parameters<Parameters<typeof http.get>[1]>[0],
		  ) => Promise<TransactionArrayResponse> | TransactionArrayResponse),
	options?: RequestHandlerOptions,
) => {
	return http.get(
		"*/members/me/transactions",
		async (info) => {
			await delay(1000);

			return new HttpResponse(
				JSON.stringify(
					overrideResponse !== undefined
						? typeof overrideResponse === "function"
							? await overrideResponse(info)
							: overrideResponse
						: getGetCurrentMemberTransactionsResponseMock(),
				),
				{ status: 200, headers: { "Content-Type": "application/json" } },
			);
		},
		options,
	);
};
export const getMembersMock = () => [
	getListMembersMockHandler(),
	getCreateMemberMockHandler(),
	getGetMemberByIdMockHandler(),
	getUpdateMemberMockHandler(),
	getDeleteMemberMockHandler(),
	getRenewCurrentMemberMockHandler(),
	getGetCurrentMemberTransactionsMockHandler(),
];
