/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * Parking Management API
 * API for managing users, parking levels, vehicles, and transactions for a parking facility.
This documentation provides a base for all the resources defined in the database schema.

 * OpenAPI spec version: 1.0.0
 */
import { faker } from "@faker-js/faker";
import type { RequestHandlerOptions } from "msw";
import { delay, HttpResponse, http } from "msw";

import type {
	MemberArrayResponse,
	MemberResponse,
	SuccessResponse,
	TransactionArrayResponse,
} from ".././models";

export const getListMembersResponseMock = (
	overrideResponse: Partial<MemberArrayResponse> = {},
): MemberArrayResponse => ({
	success: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
	message: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	data: faker.helpers.arrayElement([
		Array.from(
			{ length: faker.number.int({ min: 1, max: 10 }) },
			(_, i) => i + 1,
		).map(() => ({
			id: faker.helpers.arrayElement([
				faker.number.int({ min: undefined, max: undefined }),
				undefined,
			]),
			userId: faker.helpers.arrayElement([
				faker.number.int({ min: undefined, max: undefined }),
				undefined,
			]),
			joinedAt: faker.helpers.arrayElement([
				`${faker.date.past().toISOString().split(".")[0]}Z`,
				undefined,
			]),
			endedAt: faker.helpers.arrayElement([
				`${faker.date.past().toISOString().split(".")[0]}Z`,
				undefined,
			]),
		})),
		undefined,
	]),
	...overrideResponse,
});

export const getCreateMemberResponseMock = (
	overrideResponse: Partial<MemberResponse> = {},
): MemberResponse => ({
	success: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
	message: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	data: faker.helpers.arrayElement([
		{
			id: faker.helpers.arrayElement([
				faker.number.int({ min: undefined, max: undefined }),
				undefined,
			]),
			userId: faker.helpers.arrayElement([
				faker.number.int({ min: undefined, max: undefined }),
				undefined,
			]),
			joinedAt: faker.helpers.arrayElement([
				`${faker.date.past().toISOString().split(".")[0]}Z`,
				undefined,
			]),
			endedAt: faker.helpers.arrayElement([
				`${faker.date.past().toISOString().split(".")[0]}Z`,
				undefined,
			]),
		},
		undefined,
	]),
	...overrideResponse,
});

export const getGetMemberByIdResponseMock = (
	overrideResponse: Partial<MemberResponse> = {},
): MemberResponse => ({
	success: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
	message: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	data: faker.helpers.arrayElement([
		{
			id: faker.helpers.arrayElement([
				faker.number.int({ min: undefined, max: undefined }),
				undefined,
			]),
			userId: faker.helpers.arrayElement([
				faker.number.int({ min: undefined, max: undefined }),
				undefined,
			]),
			joinedAt: faker.helpers.arrayElement([
				`${faker.date.past().toISOString().split(".")[0]}Z`,
				undefined,
			]),
			endedAt: faker.helpers.arrayElement([
				`${faker.date.past().toISOString().split(".")[0]}Z`,
				undefined,
			]),
		},
		undefined,
	]),
	...overrideResponse,
});

export const getUpdateMemberResponseMock = (
	overrideResponse: Partial<MemberResponse> = {},
): MemberResponse => ({
	success: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
	message: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	data: faker.helpers.arrayElement([
		{
			id: faker.helpers.arrayElement([
				faker.number.int({ min: undefined, max: undefined }),
				undefined,
			]),
			userId: faker.helpers.arrayElement([
				faker.number.int({ min: undefined, max: undefined }),
				undefined,
			]),
			joinedAt: faker.helpers.arrayElement([
				`${faker.date.past().toISOString().split(".")[0]}Z`,
				undefined,
			]),
			endedAt: faker.helpers.arrayElement([
				`${faker.date.past().toISOString().split(".")[0]}Z`,
				undefined,
			]),
		},
		undefined,
	]),
	...overrideResponse,
});

export const getDeleteMemberResponseMock = (
	overrideResponse: Partial<SuccessResponse> = {},
): SuccessResponse => ({
	success: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
	message: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	data: faker.helpers.arrayElement([{}, undefined]),
	...overrideResponse,
});

export const getRenewCurrentMemberResponseMock = (
	overrideResponse: Partial<MemberResponse> = {},
): MemberResponse => ({
	success: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
	message: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	data: faker.helpers.arrayElement([
		{
			id: faker.helpers.arrayElement([
				faker.number.int({ min: undefined, max: undefined }),
				undefined,
			]),
			userId: faker.helpers.arrayElement([
				faker.number.int({ min: undefined, max: undefined }),
				undefined,
			]),
			joinedAt: faker.helpers.arrayElement([
				`${faker.date.past().toISOString().split(".")[0]}Z`,
				undefined,
			]),
			endedAt: faker.helpers.arrayElement([
				`${faker.date.past().toISOString().split(".")[0]}Z`,
				undefined,
			]),
		},
		undefined,
	]),
	...overrideResponse,
});

export const getGetCurrentMemberTransactionsResponseMock = (
	overrideResponse: Partial<TransactionArrayResponse> = {},
): TransactionArrayResponse => ({
	success: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
	message: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	data: faker.helpers.arrayElement([
		Array.from(
			{ length: faker.number.int({ min: 1, max: 10 }) },
			(_, i) => i + 1,
		).map(() => ({
			id: faker.helpers.arrayElement([
				faker.number.int({ min: undefined, max: undefined }),
				undefined,
			]),
			status: faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				undefined,
			]),
			paidAmount: faker.helpers.arrayElement([
				faker.helpers.arrayElement([
					faker.number.float({
						min: undefined,
						max: undefined,
						fractionDigits: 2,
					}),
					null,
				]),
				undefined,
			]),
			accessCode: faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				undefined,
			]),
			userId: faker.helpers.arrayElement([
				faker.helpers.arrayElement([
					faker.number.int({ min: undefined, max: undefined }),
					null,
				]),
				undefined,
			]),
			vehicleDetailId: faker.helpers.arrayElement([
				faker.number.int({ min: undefined, max: undefined }),
				undefined,
			]),
			parkingLevelId: faker.helpers.arrayElement([
				faker.number.int({ min: undefined, max: undefined }),
				undefined,
			]),
			createdAt: faker.helpers.arrayElement([
				`${faker.date.past().toISOString().split(".")[0]}Z`,
				undefined,
			]),
			updatedAt: faker.helpers.arrayElement([
				`${faker.date.past().toISOString().split(".")[0]}Z`,
				undefined,
			]),
		})),
		undefined,
	]),
	...overrideResponse,
});

export const getListMembersMockHandler = (
	overrideResponse?:
		| MemberArrayResponse
		| ((
				info: Parameters<Parameters<typeof http.get>[1]>[0],
		  ) => Promise<MemberArrayResponse> | MemberArrayResponse),
	options?: RequestHandlerOptions,
) => {
	return http.get(
		"*/members",
		async (info) => {
			await delay(1000);

			return new HttpResponse(
				JSON.stringify(
					overrideResponse !== undefined
						? typeof overrideResponse === "function"
							? await overrideResponse(info)
							: overrideResponse
						: getListMembersResponseMock(),
				),
				{ status: 200, headers: { "Content-Type": "application/json" } },
			);
		},
		options,
	);
};

export const getCreateMemberMockHandler = (
	overrideResponse?:
		| MemberResponse
		| ((
				info: Parameters<Parameters<typeof http.post>[1]>[0],
		  ) => Promise<MemberResponse> | MemberResponse),
	options?: RequestHandlerOptions,
) => {
	return http.post(
		"*/members",
		async (info) => {
			await delay(1000);

			return new HttpResponse(
				JSON.stringify(
					overrideResponse !== undefined
						? typeof overrideResponse === "function"
							? await overrideResponse(info)
							: overrideResponse
						: getCreateMemberResponseMock(),
				),
				{ status: 201, headers: { "Content-Type": "application/json" } },
			);
		},
		options,
	);
};

export const getGetMemberByIdMockHandler = (
	overrideResponse?:
		| MemberResponse
		| ((
				info: Parameters<Parameters<typeof http.get>[1]>[0],
		  ) => Promise<MemberResponse> | MemberResponse),
	options?: RequestHandlerOptions,
) => {
	return http.get(
		"*/members/:id",
		async (info) => {
			await delay(1000);

			return new HttpResponse(
				JSON.stringify(
					overrideResponse !== undefined
						? typeof overrideResponse === "function"
							? await overrideResponse(info)
							: overrideResponse
						: getGetMemberByIdResponseMock(),
				),
				{ status: 200, headers: { "Content-Type": "application/json" } },
			);
		},
		options,
	);
};

export const getUpdateMemberMockHandler = (
	overrideResponse?:
		| MemberResponse
		| ((
				info: Parameters<Parameters<typeof http.put>[1]>[0],
		  ) => Promise<MemberResponse> | MemberResponse),
	options?: RequestHandlerOptions,
) => {
	return http.put(
		"*/members/:id",
		async (info) => {
			await delay(1000);

			return new HttpResponse(
				JSON.stringify(
					overrideResponse !== undefined
						? typeof overrideResponse === "function"
							? await overrideResponse(info)
							: overrideResponse
						: getUpdateMemberResponseMock(),
				),
				{ status: 200, headers: { "Content-Type": "application/json" } },
			);
		},
		options,
	);
};

export const getDeleteMemberMockHandler = (
	overrideResponse?:
		| SuccessResponse
		| ((
				info: Parameters<Parameters<typeof http.delete>[1]>[0],
		  ) => Promise<SuccessResponse> | SuccessResponse),
	options?: RequestHandlerOptions,
) => {
	return http.delete(
		"*/members/:id",
		async (info) => {
			await delay(1000);

			return new HttpResponse(
				JSON.stringify(
					overrideResponse !== undefined
						? typeof overrideResponse === "function"
							? await overrideResponse(info)
							: overrideResponse
						: getDeleteMemberResponseMock(),
				),
				{ status: 200, headers: { "Content-Type": "application/json" } },
			);
		},
		options,
	);
};

export const getRenewCurrentMemberMockHandler = (
	overrideResponse?:
		| MemberResponse
		| ((
				info: Parameters<Parameters<typeof http.post>[1]>[0],
		  ) => Promise<MemberResponse> | MemberResponse),
	options?: RequestHandlerOptions,
) => {
	return http.post(
		"*/members/me/renew",
		async (info) => {
			await delay(1000);

			return new HttpResponse(
				JSON.stringify(
					overrideResponse !== undefined
						? typeof overrideResponse === "function"
							? await overrideResponse(info)
							: overrideResponse
						: getRenewCurrentMemberResponseMock(),
				),
				{ status: 200, headers: { "Content-Type": "application/json" } },
			);
		},
		options,
	);
};

export const getGetCurrentMemberTransactionsMockHandler = (
	overrideResponse?:
		| TransactionArrayResponse
		| ((
				info: Parameters<Parameters<typeof http.get>[1]>[0],
		  ) => Promise<TransactionArrayResponse> | TransactionArrayResponse),
	options?: RequestHandlerOptions,
) => {
	return http.get(
		"*/members/me/transactions",
		async (info) => {
			await delay(1000);

			return new HttpResponse(
				JSON.stringify(
					overrideResponse !== undefined
						? typeof overrideResponse === "function"
							? await overrideResponse(info)
							: overrideResponse
						: getGetCurrentMemberTransactionsResponseMock(),
				),
				{ status: 200, headers: { "Content-Type": "application/json" } },
			);
		},
		options,
	);
};
export const getMembersMock = () => [
	getListMembersMockHandler(),
	getCreateMemberMockHandler(),
	getGetMemberByIdMockHandler(),
	getUpdateMemberMockHandler(),
	getDeleteMemberMockHandler(),
	getRenewCurrentMemberMockHandler(),
	getGetCurrentMemberTransactionsMockHandler(),
];
