/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * Parking Management API
 * API for managing users, parking levels, vehicles, and transactions for a parking facility.
This documentation provides a base for all the resources defined in the database schema.

 * OpenAPI spec version: 1.0.0
 */
import { faker } from "@faker-js/faker";
import type { RequestHandlerOptions } from "msw";
import { delay, HttpResponse, http } from "msw";

import type {
	SuccessResponse,
	VehicleDetailArrayResponse,
	VehicleDetailResponse,
} from ".././models";

export const getGetVehicleDetailsResponseMock = (
	overrideResponse: Partial<VehicleDetailArrayResponse> = {},
): VehicleDetailArrayResponse => ({
	success: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
	message: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	data: faker.helpers.arrayElement([
		Array.from(
			{ length: faker.number.int({ min: 1, max: 10 }) },
			(_, i) => i + 1,
		).map(() => ({
			id: faker.helpers.arrayElement([
				faker.number.int({ min: undefined, max: undefined }),
				undefined,
			]),
			plateNumber: faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				undefined,
			]),
			categoryId: faker.helpers.arrayElement([
				faker.number.int({ min: undefined, max: undefined }),
				undefined,
			]),
		})),
		undefined,
	]),
	...overrideResponse,
});

export const getPostVehicleDetailsResponseMock = (
	overrideResponse: Partial<VehicleDetailResponse> = {},
): VehicleDetailResponse => ({
	success: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
	message: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	data: faker.helpers.arrayElement([
		{
			id: faker.helpers.arrayElement([
				faker.number.int({ min: undefined, max: undefined }),
				undefined,
			]),
			plateNumber: faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				undefined,
			]),
			categoryId: faker.helpers.arrayElement([
				faker.number.int({ min: undefined, max: undefined }),
				undefined,
			]),
		},
		undefined,
	]),
	...overrideResponse,
});

export const getGetVehicleDetailsIdResponseMock = (
	overrideResponse: Partial<VehicleDetailResponse> = {},
): VehicleDetailResponse => ({
	success: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
	message: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	data: faker.helpers.arrayElement([
		{
			id: faker.helpers.arrayElement([
				faker.number.int({ min: undefined, max: undefined }),
				undefined,
			]),
			plateNumber: faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				undefined,
			]),
			categoryId: faker.helpers.arrayElement([
				faker.number.int({ min: undefined, max: undefined }),
				undefined,
			]),
		},
		undefined,
	]),
	...overrideResponse,
});

export const getPutVehicleDetailsIdResponseMock = (
	overrideResponse: Partial<VehicleDetailResponse> = {},
): VehicleDetailResponse => ({
	success: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
	message: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	data: faker.helpers.arrayElement([
		{
			id: faker.helpers.arrayElement([
				faker.number.int({ min: undefined, max: undefined }),
				undefined,
			]),
			plateNumber: faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				undefined,
			]),
			categoryId: faker.helpers.arrayElement([
				faker.number.int({ min: undefined, max: undefined }),
				undefined,
			]),
		},
		undefined,
	]),
	...overrideResponse,
});

export const getDeleteVehicleDetailsIdResponseMock = (
	overrideResponse: Partial<SuccessResponse> = {},
): SuccessResponse => ({
	success: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
	message: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	data: faker.helpers.arrayElement([{}, undefined]),
	...overrideResponse,
});

export const getGetVehicleDetailsMockHandler = (
	overrideResponse?:
		| VehicleDetailArrayResponse
		| ((
				info: Parameters<Parameters<typeof http.get>[1]>[0],
		  ) => Promise<VehicleDetailArrayResponse> | VehicleDetailArrayResponse),
	options?: RequestHandlerOptions,
) => {
	return http.get(
		"*/vehicle-details",
		async (info) => {
			await delay(1000);

			return new HttpResponse(
				JSON.stringify(
					overrideResponse !== undefined
						? typeof overrideResponse === "function"
							? await overrideResponse(info)
							: overrideResponse
						: getGetVehicleDetailsResponseMock(),
				),
				{ status: 200, headers: { "Content-Type": "application/json" } },
			);
		},
		options,
	);
};

export const getPostVehicleDetailsMockHandler = (
	overrideResponse?:
		| VehicleDetailResponse
		| ((
				info: Parameters<Parameters<typeof http.post>[1]>[0],
		  ) => Promise<VehicleDetailResponse> | VehicleDetailResponse),
	options?: RequestHandlerOptions,
) => {
	return http.post(
		"*/vehicle-details",
		async (info) => {
			await delay(1000);

			return new HttpResponse(
				JSON.stringify(
					overrideResponse !== undefined
						? typeof overrideResponse === "function"
							? await overrideResponse(info)
							: overrideResponse
						: getPostVehicleDetailsResponseMock(),
				),
				{ status: 201, headers: { "Content-Type": "application/json" } },
			);
		},
		options,
	);
};

export const getGetVehicleDetailsIdMockHandler = (
	overrideResponse?:
		| VehicleDetailResponse
		| ((
				info: Parameters<Parameters<typeof http.get>[1]>[0],
		  ) => Promise<VehicleDetailResponse> | VehicleDetailResponse),
	options?: RequestHandlerOptions,
) => {
	return http.get(
		"*/vehicle-details/:id",
		async (info) => {
			await delay(1000);

			return new HttpResponse(
				JSON.stringify(
					overrideResponse !== undefined
						? typeof overrideResponse === "function"
							? await overrideResponse(info)
							: overrideResponse
						: getGetVehicleDetailsIdResponseMock(),
				),
				{ status: 200, headers: { "Content-Type": "application/json" } },
			);
		},
		options,
	);
};

export const getPutVehicleDetailsIdMockHandler = (
	overrideResponse?:
		| VehicleDetailResponse
		| ((
				info: Parameters<Parameters<typeof http.put>[1]>[0],
		  ) => Promise<VehicleDetailResponse> | VehicleDetailResponse),
	options?: RequestHandlerOptions,
) => {
	return http.put(
		"*/vehicle-details/:id",
		async (info) => {
			await delay(1000);

			return new HttpResponse(
				JSON.stringify(
					overrideResponse !== undefined
						? typeof overrideResponse === "function"
							? await overrideResponse(info)
							: overrideResponse
						: getPutVehicleDetailsIdResponseMock(),
				),
				{ status: 200, headers: { "Content-Type": "application/json" } },
			);
		},
		options,
	);
};

export const getDeleteVehicleDetailsIdMockHandler = (
	overrideResponse?:
		| SuccessResponse
		| ((
				info: Parameters<Parameters<typeof http.delete>[1]>[0],
		  ) => Promise<SuccessResponse> | SuccessResponse),
	options?: RequestHandlerOptions,
) => {
	return http.delete(
		"*/vehicle-details/:id",
		async (info) => {
			await delay(1000);

			return new HttpResponse(
				JSON.stringify(
					overrideResponse !== undefined
						? typeof overrideResponse === "function"
							? await overrideResponse(info)
							: overrideResponse
						: getDeleteVehicleDetailsIdResponseMock(),
				),
				{ status: 200, headers: { "Content-Type": "application/json" } },
			);
		},
		options,
	);
};
export const getVehicleDetailsMock = () => [
	getGetVehicleDetailsMockHandler(),
	getPostVehicleDetailsMockHandler(),
	getGetVehicleDetailsIdMockHandler(),
	getPutVehicleDetailsIdMockHandler(),
	getDeleteVehicleDetailsIdMockHandler(),
];
