/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * Parking Management API
 * API for managing users, parking levels, vehicles, and transactions for a parking facility.
This documentation provides a base for all the resources defined in the database schema.

 * OpenAPI spec version: 1.0.0
 */
import type { ApiErrorResponseDataErrorMetaItem } from "./apiErrorResponseDataErrorMetaItem";

/**
 * @nullable
 */
export type ApiErrorResponseData = {
	/** A unique, machine-readable error code. */
	errorCode: string;
	/** Optional metadata for validation errors. */
	errorMeta?: ApiErrorResponseDataErrorMetaItem[];
} | null;
