/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * Parking Management API
 * API for managing users, parking levels, vehicles, and transactions for a parking facility.
This documentation provides a base for all the resources defined in the database schema.

 * OpenAPI spec version: 1.0.0
 */

/**
 * Summary data for the admin or member dashboard.
 */
export interface DashboardSummary {
	/** (Admin) Total number of currently parked vehicles. */
	activeTransactions?: number;
	/** (Admin) Total parking capacity. */
	totalCapacity?: number;
	/** (Member) Status of the member's subscription. */
	membershipStatus?: string;
	/** (Member) The date the membership expires. */
	membershipEndsAt?: string;
}
