/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * Parking Management API
 * API for managing users, parking levels, vehicles, and transactions for a parking facility.
This documentation provides a base for all the resources defined in the database schema.

 * OpenAPI spec version: 1.0.0
 */

/**
 * Payload for renewing a membership using a specific plan ID.
 */
export interface MembershipRenewal {
	/** The ID of the membership plan being purchased. */
	membershipPlanId: number;
}
