/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * Parking Management API
 * API for managing users, parking levels, vehicles, and transactions for a parking facility.
This documentation provides a base for all the resources defined in the database schema.

 * OpenAPI spec version: 1.0.0
 */

export interface ParkingLevel {
	id: number;
	name: string;
	/** Maximum allowed weight in kilograms for this level. */
	maxWeight: number;
}
