/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * Parking Management API
 * API for managing users, parking levels, vehicles, and transactions for a parking facility.
This documentation provides a base for all the resources defined in the database schema.

 * OpenAPI spec version: 1.0.0
 */

export interface PriceCreate {
	categoryId: number;
	amount: number;
	/** Business rule type for the price. */
	type: string;
	/**
	 * Duration in hours for INITIAL_BLOCK type. Required if type is 'INITIAL_BLOCK'.
	 * @nullable
	 */
	block_hours?: number | null;
	is_active?: boolean;
	/** @nullable */
	valid_from?: string | null;
	/** @nullable */
	valid_until?: string | null;
}
