/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * Parking Management API
 * API for managing users, parking levels, vehicles, and transactions for a parking facility.
This documentation provides a base for all the resources defined in the database schema.

 * OpenAPI spec version: 1.0.0
 */

export interface Transaction {
	id?: number;
	/** Current status of the transaction (e.g., ACTIVE, PAID, COMPLETED). */
	status?: string;
	/** @nullable */
	paidAmount?: number | null;
	/** Unique code for this transaction. */
	accessCode?: string;
	/** @nullable */
	userId?: number | null;
	vehicleDetailId?: number;
	parkingLevelId?: number;
	createdAt?: string;
	updatedAt?: string;
}
