/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * Parking Management API
 * API for managing users, parking levels, vehicles, and transactions for a parking facility.
This documentation provides a base for all the resources defined in the database schema.

 * OpenAPI spec version: 1.0.0
 */
import type { TransactionStatus } from "./transactionStatus";

export interface Transaction {
	id: number;
	/** Status of the transaction, indicating vehicle entry or exit. */
	status: TransactionStatus;
	/** @nullable */
	paidAmount: number | null;
	/** Unique code for this transaction. */
	accessCode: string;
	/** @nullable */
	userId: number | null;
	vehicleDetailId: number;
	parkingLevelId: number;
	createdAt: string;
	updatedAt: string;
}
