/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * Parking Management API
 * API for managing users, parking levels, vehicles, and transactions for a parking facility.
This documentation provides a base for all the resources defined in the database schema.

 * OpenAPI spec version: 1.0.0
 */

import type { ParkingLevel } from "./parkingLevel";
import type { TransactionStatus } from "./transactionStatus";
import type { User } from "./user";
import type { VehicleDetail } from "./vehicleDetail";

export interface Transaction {
	id: number;
	/** Status of the transaction, indicating vehicle entry or exit. */
	status: TransactionStatus;
	/** @nullable */
	paid_amount?: number | null;
	/** Unique code for this transaction. */
	access_code: string;
	/** @nullable */
	user_id?: number | null;
	/**
	 * Expanded user information when available.
	 * @nullable
	 */
	user?: User;
	vehicle_detail_id: number;
	/** Vehicle detail associated to this transaction. */
	vehicleDetail: VehicleDetail;
	parking_level_id: number;
	/** Parking level information for this transaction. */
	parkingLevel: ParkingLevel;
	created_at: string;
	updated_at: string;
}
