/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MembersRouteRouteImport } from './routes/members/route'
import { Route as EntryRouteRouteImport } from './routes/entry/route'
import { Route as CheckRouteRouteImport } from './routes/check/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as RouteRouteImport } from './routes/route'
import { Route as MembersIndexRouteImport } from './routes/members/index'
import { Route as EntryIndexRouteImport } from './routes/entry/index'
import { Route as CheckIndexRouteImport } from './routes/check/index'
import { Route as EntrySuccessRouteImport } from './routes/entry/success'
import { Route as AuthSignInRouteImport } from './routes/_auth/sign-in'
import { Route as AuthSignUpIndexRouteImport } from './routes/_auth/sign-up/index'
import { Route as AuthSignUpUpgradeRouteImport } from './routes/_auth/sign-up/upgrade'
import { Route as AuthSignUpSuccessRouteImport } from './routes/_auth/sign-up/success'

const MembersRouteRoute = MembersRouteRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => rootRouteImport,
} as any)
const EntryRouteRoute = EntryRouteRouteImport.update({
  id: '/entry',
  path: '/entry',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckRouteRoute = CheckRouteRouteImport.update({
  id: '/check',
  path: '/check',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const RouteRoute = RouteRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersIndexRoute = MembersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MembersRouteRoute,
} as any)
const EntryIndexRoute = EntryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EntryRouteRoute,
} as any)
const CheckIndexRoute = CheckIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CheckRouteRoute,
} as any)
const EntrySuccessRoute = EntrySuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => EntryRouteRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignUpIndexRoute = AuthSignUpIndexRouteImport.update({
  id: '/sign-up/',
  path: '/sign-up/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignUpUpgradeRoute = AuthSignUpUpgradeRouteImport.update({
  id: '/sign-up/upgrade',
  path: '/sign-up/upgrade',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignUpSuccessRoute = AuthSignUpSuccessRouteImport.update({
  id: '/sign-up/success',
  path: '/sign-up/success',
  getParentRoute: () => AuthRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof RouteRoute
  '/check': typeof CheckRouteRouteWithChildren
  '/entry': typeof EntryRouteRouteWithChildren
  '/members': typeof MembersRouteRouteWithChildren
  '/sign-in': typeof AuthSignInRoute
  '/entry/success': typeof EntrySuccessRoute
  '/check/': typeof CheckIndexRoute
  '/entry/': typeof EntryIndexRoute
  '/members/': typeof MembersIndexRoute
  '/sign-up/success': typeof AuthSignUpSuccessRoute
  '/sign-up/upgrade': typeof AuthSignUpUpgradeRoute
  '/sign-up': typeof AuthSignUpIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof RouteRoute
  '/sign-in': typeof AuthSignInRoute
  '/entry/success': typeof EntrySuccessRoute
  '/check': typeof CheckIndexRoute
  '/entry': typeof EntryIndexRoute
  '/members': typeof MembersIndexRoute
  '/sign-up/success': typeof AuthSignUpSuccessRoute
  '/sign-up/upgrade': typeof AuthSignUpUpgradeRoute
  '/sign-up': typeof AuthSignUpIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof RouteRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/check': typeof CheckRouteRouteWithChildren
  '/entry': typeof EntryRouteRouteWithChildren
  '/members': typeof MembersRouteRouteWithChildren
  '/_auth/sign-in': typeof AuthSignInRoute
  '/entry/success': typeof EntrySuccessRoute
  '/check/': typeof CheckIndexRoute
  '/entry/': typeof EntryIndexRoute
  '/members/': typeof MembersIndexRoute
  '/_auth/sign-up/success': typeof AuthSignUpSuccessRoute
  '/_auth/sign-up/upgrade': typeof AuthSignUpUpgradeRoute
  '/_auth/sign-up/': typeof AuthSignUpIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/check'
    | '/entry'
    | '/members'
    | '/sign-in'
    | '/entry/success'
    | '/check/'
    | '/entry/'
    | '/members/'
    | '/sign-up/success'
    | '/sign-up/upgrade'
    | '/sign-up'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/entry/success'
    | '/check'
    | '/entry'
    | '/members'
    | '/sign-up/success'
    | '/sign-up/upgrade'
    | '/sign-up'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/check'
    | '/entry'
    | '/members'
    | '/_auth/sign-in'
    | '/entry/success'
    | '/check/'
    | '/entry/'
    | '/members/'
    | '/_auth/sign-up/success'
    | '/_auth/sign-up/upgrade'
    | '/_auth/sign-up/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  RouteRoute: typeof RouteRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  CheckRouteRoute: typeof CheckRouteRouteWithChildren
  EntryRouteRoute: typeof EntryRouteRouteWithChildren
  MembersRouteRoute: typeof MembersRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/members': {
      id: '/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof MembersRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entry': {
      id: '/entry'
      path: '/entry'
      fullPath: '/entry'
      preLoaderRoute: typeof EntryRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/check': {
      id: '/check'
      path: '/check'
      fullPath: '/check'
      preLoaderRoute: typeof CheckRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof RouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members/': {
      id: '/members/'
      path: '/'
      fullPath: '/members/'
      preLoaderRoute: typeof MembersIndexRouteImport
      parentRoute: typeof MembersRouteRoute
    }
    '/entry/': {
      id: '/entry/'
      path: '/'
      fullPath: '/entry/'
      preLoaderRoute: typeof EntryIndexRouteImport
      parentRoute: typeof EntryRouteRoute
    }
    '/check/': {
      id: '/check/'
      path: '/'
      fullPath: '/check/'
      preLoaderRoute: typeof CheckIndexRouteImport
      parentRoute: typeof CheckRouteRoute
    }
    '/entry/success': {
      id: '/entry/success'
      path: '/success'
      fullPath: '/entry/success'
      preLoaderRoute: typeof EntrySuccessRouteImport
      parentRoute: typeof EntryRouteRoute
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/sign-up/': {
      id: '/_auth/sign-up/'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/sign-up/upgrade': {
      id: '/_auth/sign-up/upgrade'
      path: '/sign-up/upgrade'
      fullPath: '/sign-up/upgrade'
      preLoaderRoute: typeof AuthSignUpUpgradeRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/sign-up/success': {
      id: '/_auth/sign-up/success'
      path: '/sign-up/success'
      fullPath: '/sign-up/success'
      preLoaderRoute: typeof AuthSignUpSuccessRouteImport
      parentRoute: typeof AuthRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpSuccessRoute: typeof AuthSignUpSuccessRoute
  AuthSignUpUpgradeRoute: typeof AuthSignUpUpgradeRoute
  AuthSignUpIndexRoute: typeof AuthSignUpIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpSuccessRoute: AuthSignUpSuccessRoute,
  AuthSignUpUpgradeRoute: AuthSignUpUpgradeRoute,
  AuthSignUpIndexRoute: AuthSignUpIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface CheckRouteRouteChildren {
  CheckIndexRoute: typeof CheckIndexRoute
}

const CheckRouteRouteChildren: CheckRouteRouteChildren = {
  CheckIndexRoute: CheckIndexRoute,
}

const CheckRouteRouteWithChildren = CheckRouteRoute._addFileChildren(
  CheckRouteRouteChildren,
)

interface EntryRouteRouteChildren {
  EntrySuccessRoute: typeof EntrySuccessRoute
  EntryIndexRoute: typeof EntryIndexRoute
}

const EntryRouteRouteChildren: EntryRouteRouteChildren = {
  EntrySuccessRoute: EntrySuccessRoute,
  EntryIndexRoute: EntryIndexRoute,
}

const EntryRouteRouteWithChildren = EntryRouteRoute._addFileChildren(
  EntryRouteRouteChildren,
)

interface MembersRouteRouteChildren {
  MembersIndexRoute: typeof MembersIndexRoute
}

const MembersRouteRouteChildren: MembersRouteRouteChildren = {
  MembersIndexRoute: MembersIndexRoute,
}

const MembersRouteRouteWithChildren = MembersRouteRoute._addFileChildren(
  MembersRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  RouteRoute: RouteRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  CheckRouteRoute: CheckRouteRouteWithChildren,
  EntryRouteRoute: EntryRouteRouteWithChildren,
  MembersRouteRoute: MembersRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
