/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * Parking Management API
 * API for managing users, parking levels, vehicles, and transactions for a parking facility.
This documentation provides a base for all the resources defined in the database schema.

 * OpenAPI spec version: 1.0.0
 */
import { faker } from "@faker-js/faker";
import type { RequestHandlerOptions } from "msw";
import { delay, HttpResponse, http } from "msw";

import type {
	BaseResponse,
	CategoryArrayResponse,
	CategoryResponse,
} from ".././models";

export const getListCategoriesResponseMock = (): CategoryArrayResponse => ({
	...{
		success: faker.datatype.boolean(),
		message: faker.string.alpha({ length: { min: 10, max: 20 } }),
	},
	...{
		data: Array.from(
			{ length: faker.number.int({ min: 1, max: 10 }) },
			(_, i) => i + 1,
		).map(() => ({
			id: faker.number.int({ min: undefined, max: undefined }),
			name: faker.string.alpha({ length: { min: 10, max: 20 } }),
			weight: faker.number.float({
				min: undefined,
				max: undefined,
				fractionDigits: 2,
			}),
			icon: faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				undefined,
			]),
			thumbnail: faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				undefined,
			]),
		})),
	},
});

export const getCreateCategoryResponseMock = (): CategoryResponse => ({
	...{
		success: faker.datatype.boolean(),
		message: faker.string.alpha({ length: { min: 10, max: 20 } }),
	},
	...{
		data: {
			id: faker.number.int({ min: undefined, max: undefined }),
			name: faker.string.alpha({ length: { min: 10, max: 20 } }),
			weight: faker.number.float({
				min: undefined,
				max: undefined,
				fractionDigits: 2,
			}),
			icon: faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				undefined,
			]),
			thumbnail: faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				undefined,
			]),
		},
	},
});

export const getGetCategoryByIdResponseMock = (): CategoryResponse => ({
	...{
		success: faker.datatype.boolean(),
		message: faker.string.alpha({ length: { min: 10, max: 20 } }),
	},
	...{
		data: {
			id: faker.number.int({ min: undefined, max: undefined }),
			name: faker.string.alpha({ length: { min: 10, max: 20 } }),
			weight: faker.number.float({
				min: undefined,
				max: undefined,
				fractionDigits: 2,
			}),
			icon: faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				undefined,
			]),
			thumbnail: faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				undefined,
			]),
		},
	},
});

export const getUpdateCategoryResponseMock = (): CategoryResponse => ({
	...{
		success: faker.datatype.boolean(),
		message: faker.string.alpha({ length: { min: 10, max: 20 } }),
	},
	...{
		data: {
			id: faker.number.int({ min: undefined, max: undefined }),
			name: faker.string.alpha({ length: { min: 10, max: 20 } }),
			weight: faker.number.float({
				min: undefined,
				max: undefined,
				fractionDigits: 2,
			}),
			icon: faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				undefined,
			]),
			thumbnail: faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				undefined,
			]),
		},
	},
});

export const getDeleteCategoryResponseMock = (
	overrideResponse: Partial<BaseResponse> = {},
): BaseResponse => ({
	success: faker.datatype.boolean(),
	message: faker.string.alpha({ length: { min: 10, max: 20 } }),
	...overrideResponse,
});

export const getListCategoriesMockHandler = (
	overrideResponse?:
		| CategoryArrayResponse
		| ((
				info: Parameters<Parameters<typeof http.get>[1]>[0],
		  ) => Promise<CategoryArrayResponse> | CategoryArrayResponse),
	options?: RequestHandlerOptions,
) => {
	return http.get(
		"*/categories",
		async (info) => {
			await delay(1000);

			return new HttpResponse(
				JSON.stringify(
					overrideResponse !== undefined
						? typeof overrideResponse === "function"
							? await overrideResponse(info)
							: overrideResponse
						: getListCategoriesResponseMock(),
				),
				{ status: 200, headers: { "Content-Type": "application/json" } },
			);
		},
		options,
	);
};

export const getCreateCategoryMockHandler = (
	overrideResponse?:
		| CategoryResponse
		| ((
				info: Parameters<Parameters<typeof http.post>[1]>[0],
		  ) => Promise<CategoryResponse> | CategoryResponse),
	options?: RequestHandlerOptions,
) => {
	return http.post(
		"*/categories",
		async (info) => {
			await delay(1000);

			return new HttpResponse(
				JSON.stringify(
					overrideResponse !== undefined
						? typeof overrideResponse === "function"
							? await overrideResponse(info)
							: overrideResponse
						: getCreateCategoryResponseMock(),
				),
				{ status: 201, headers: { "Content-Type": "application/json" } },
			);
		},
		options,
	);
};

export const getGetCategoryByIdMockHandler = (
	overrideResponse?:
		| CategoryResponse
		| ((
				info: Parameters<Parameters<typeof http.get>[1]>[0],
		  ) => Promise<CategoryResponse> | CategoryResponse),
	options?: RequestHandlerOptions,
) => {
	return http.get(
		"*/categories/:id",
		async (info) => {
			await delay(1000);

			return new HttpResponse(
				JSON.stringify(
					overrideResponse !== undefined
						? typeof overrideResponse === "function"
							? await overrideResponse(info)
							: overrideResponse
						: getGetCategoryByIdResponseMock(),
				),
				{ status: 200, headers: { "Content-Type": "application/json" } },
			);
		},
		options,
	);
};

export const getUpdateCategoryMockHandler = (
	overrideResponse?:
		| CategoryResponse
		| ((
				info: Parameters<Parameters<typeof http.put>[1]>[0],
		  ) => Promise<CategoryResponse> | CategoryResponse),
	options?: RequestHandlerOptions,
) => {
	return http.put(
		"*/categories/:id",
		async (info) => {
			await delay(1000);

			return new HttpResponse(
				JSON.stringify(
					overrideResponse !== undefined
						? typeof overrideResponse === "function"
							? await overrideResponse(info)
							: overrideResponse
						: getUpdateCategoryResponseMock(),
				),
				{ status: 200, headers: { "Content-Type": "application/json" } },
			);
		},
		options,
	);
};

export const getDeleteCategoryMockHandler = (
	overrideResponse?:
		| BaseResponse
		| ((
				info: Parameters<Parameters<typeof http.delete>[1]>[0],
		  ) => Promise<BaseResponse> | BaseResponse),
	options?: RequestHandlerOptions,
) => {
	return http.delete(
		"*/categories/:id",
		async (info) => {
			await delay(1000);

			return new HttpResponse(
				JSON.stringify(
					overrideResponse !== undefined
						? typeof overrideResponse === "function"
							? await overrideResponse(info)
							: overrideResponse
						: getDeleteCategoryResponseMock(),
				),
				{ status: 200, headers: { "Content-Type": "application/json" } },
			);
		},
		options,
	);
};
export const getCategoriesMock = () => [
	getListCategoriesMockHandler(),
	getCreateCategoryMockHandler(),
	getGetCategoryByIdMockHandler(),
	getUpdateCategoryMockHandler(),
	getDeleteCategoryMockHandler(),
];
