/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * Parking Management API
 * API for managing users, parking levels, vehicles, and transactions for a parking facility.
This documentation provides a base for all the resources defined in the database schema.

 * OpenAPI spec version: 1.0.0
 */
import { faker } from "@faker-js/faker";
import type { RequestHandlerOptions } from "msw";
import { delay, HttpResponse, http } from "msw";

import type {
	PriceArrayResponse,
	PriceResponse,
	SuccessResponse,
} from ".././models";

export const getListPricesResponseMock = (
	overrideResponse: Partial<PriceArrayResponse> = {},
): PriceArrayResponse => ({
	success: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
	message: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	data: faker.helpers.arrayElement([
		Array.from(
			{ length: faker.number.int({ min: 1, max: 10 }) },
			(_, i) => i + 1,
		).map(() => ({
			id: faker.helpers.arrayElement([
				faker.number.int({ min: undefined, max: undefined }),
				undefined,
			]),
			categoryId: faker.helpers.arrayElement([
				faker.number.int({ min: undefined, max: undefined }),
				undefined,
			]),
			amount: faker.helpers.arrayElement([
				faker.number.float({
					min: undefined,
					max: undefined,
					fractionDigits: 2,
				}),
				undefined,
			]),
		})),
		undefined,
	]),
	...overrideResponse,
});

export const getCreatePriceResponseMock = (
	overrideResponse: Partial<PriceResponse> = {},
): PriceResponse => ({
	success: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
	message: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	data: faker.helpers.arrayElement([
		{
			id: faker.helpers.arrayElement([
				faker.number.int({ min: undefined, max: undefined }),
				undefined,
			]),
			categoryId: faker.helpers.arrayElement([
				faker.number.int({ min: undefined, max: undefined }),
				undefined,
			]),
			amount: faker.helpers.arrayElement([
				faker.number.float({
					min: undefined,
					max: undefined,
					fractionDigits: 2,
				}),
				undefined,
			]),
		},
		undefined,
	]),
	...overrideResponse,
});

export const getGetPriceByIdResponseMock = (
	overrideResponse: Partial<PriceResponse> = {},
): PriceResponse => ({
	success: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
	message: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	data: faker.helpers.arrayElement([
		{
			id: faker.helpers.arrayElement([
				faker.number.int({ min: undefined, max: undefined }),
				undefined,
			]),
			categoryId: faker.helpers.arrayElement([
				faker.number.int({ min: undefined, max: undefined }),
				undefined,
			]),
			amount: faker.helpers.arrayElement([
				faker.number.float({
					min: undefined,
					max: undefined,
					fractionDigits: 2,
				}),
				undefined,
			]),
		},
		undefined,
	]),
	...overrideResponse,
});

export const getUpdatePriceResponseMock = (
	overrideResponse: Partial<PriceResponse> = {},
): PriceResponse => ({
	success: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
	message: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	data: faker.helpers.arrayElement([
		{
			id: faker.helpers.arrayElement([
				faker.number.int({ min: undefined, max: undefined }),
				undefined,
			]),
			categoryId: faker.helpers.arrayElement([
				faker.number.int({ min: undefined, max: undefined }),
				undefined,
			]),
			amount: faker.helpers.arrayElement([
				faker.number.float({
					min: undefined,
					max: undefined,
					fractionDigits: 2,
				}),
				undefined,
			]),
		},
		undefined,
	]),
	...overrideResponse,
});

export const getDeletePriceResponseMock = (
	overrideResponse: Partial<SuccessResponse> = {},
): SuccessResponse => ({
	success: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
	message: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	data: faker.helpers.arrayElement([{}, undefined]),
	...overrideResponse,
});

export const getListPricesMockHandler = (
	overrideResponse?:
		| PriceArrayResponse
		| ((
				info: Parameters<Parameters<typeof http.get>[1]>[0],
		  ) => Promise<PriceArrayResponse> | PriceArrayResponse),
	options?: RequestHandlerOptions,
) => {
	return http.get(
		"*/prices",
		async (info) => {
			await delay(1000);

			return new HttpResponse(
				JSON.stringify(
					overrideResponse !== undefined
						? typeof overrideResponse === "function"
							? await overrideResponse(info)
							: overrideResponse
						: getListPricesResponseMock(),
				),
				{ status: 200, headers: { "Content-Type": "application/json" } },
			);
		},
		options,
	);
};

export const getCreatePriceMockHandler = (
	overrideResponse?:
		| PriceResponse
		| ((
				info: Parameters<Parameters<typeof http.post>[1]>[0],
		  ) => Promise<PriceResponse> | PriceResponse),
	options?: RequestHandlerOptions,
) => {
	return http.post(
		"*/prices",
		async (info) => {
			await delay(1000);

			return new HttpResponse(
				JSON.stringify(
					overrideResponse !== undefined
						? typeof overrideResponse === "function"
							? await overrideResponse(info)
							: overrideResponse
						: getCreatePriceResponseMock(),
				),
				{ status: 201, headers: { "Content-Type": "application/json" } },
			);
		},
		options,
	);
};

export const getGetPriceByIdMockHandler = (
	overrideResponse?:
		| PriceResponse
		| ((
				info: Parameters<Parameters<typeof http.get>[1]>[0],
		  ) => Promise<PriceResponse> | PriceResponse),
	options?: RequestHandlerOptions,
) => {
	return http.get(
		"*/prices/:id",
		async (info) => {
			await delay(1000);

			return new HttpResponse(
				JSON.stringify(
					overrideResponse !== undefined
						? typeof overrideResponse === "function"
							? await overrideResponse(info)
							: overrideResponse
						: getGetPriceByIdResponseMock(),
				),
				{ status: 200, headers: { "Content-Type": "application/json" } },
			);
		},
		options,
	);
};

export const getUpdatePriceMockHandler = (
	overrideResponse?:
		| PriceResponse
		| ((
				info: Parameters<Parameters<typeof http.put>[1]>[0],
		  ) => Promise<PriceResponse> | PriceResponse),
	options?: RequestHandlerOptions,
) => {
	return http.put(
		"*/prices/:id",
		async (info) => {
			await delay(1000);

			return new HttpResponse(
				JSON.stringify(
					overrideResponse !== undefined
						? typeof overrideResponse === "function"
							? await overrideResponse(info)
							: overrideResponse
						: getUpdatePriceResponseMock(),
				),
				{ status: 200, headers: { "Content-Type": "application/json" } },
			);
		},
		options,
	);
};

export const getDeletePriceMockHandler = (
	overrideResponse?:
		| SuccessResponse
		| ((
				info: Parameters<Parameters<typeof http.delete>[1]>[0],
		  ) => Promise<SuccessResponse> | SuccessResponse),
	options?: RequestHandlerOptions,
) => {
	return http.delete(
		"*/prices/:id",
		async (info) => {
			await delay(1000);

			return new HttpResponse(
				JSON.stringify(
					overrideResponse !== undefined
						? typeof overrideResponse === "function"
							? await overrideResponse(info)
							: overrideResponse
						: getDeletePriceResponseMock(),
				),
				{ status: 200, headers: { "Content-Type": "application/json" } },
			);
		},
		options,
	);
};
export const getPricesMock = () => [
	getListPricesMockHandler(),
	getCreatePriceMockHandler(),
	getGetPriceByIdMockHandler(),
	getUpdatePriceMockHandler(),
	getDeletePriceMockHandler(),
];
